/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 whcHero.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
    const { nodes, materials } = useGLTF("/whcHero.gltf");
    return (
        <group {...props} dispose={null} scale={[0.035, 0.035, 0.035]}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.mat0} />
            <mesh geometry={nodes.mesh_1.geometry} material={materials.mat0} />
            <mesh geometry={nodes.mesh_2.geometry} material={materials.mat0} />
            <mesh geometry={nodes.mesh_3.geometry} material={materials.mat1} />
            <mesh geometry={nodes.mesh_4.geometry} material={materials.mat2} />
            <mesh geometry={nodes.mesh_5.geometry} material={materials.mat3} />
        </group>
    );
}

useGLTF.preload("/whcHero.gltf");
