name: CI / CD

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v4
            - name: Set up Nodejs
              uses: actions/setup-node@v4
              with:
                node-version: "v20.10.0"
            - name: Install dependencies
              run: |
                    npm install -g yarn
                    yarn
            - name: Setup ENV
              run: |
                  touch .env.local
                  printf "WHC_API_DOMAIN=%s\n" "${{secrets.WHC_API_DOMAIN}}" >> .env.local
                  printf "NEXT_PUBLIC_WHC_API_DOMAIN=\"%s\"\n" "${{secrets.NEXT_PUBLIC_WHC_API_DOMAIN}}" >> .env.local
                  printf "NODE_ENV=\"%s\"\n" "${{secrets.NODE_ENV}}" >> .env.local
            - name: Building app
              run: yarn build
            - name: Exposing build to the world
              run: |
                  export PM2_HOME=/root/.pm2
                  pm2 restart ecosystem.config.js
            - name: Save PM2
              run: pm2 save
